// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgv9xkzeAnni2aD4nNtwKHNv9r8NlR2Qc',
    appId: '1:452328140275:web:a0be1593e6c7711b1c3686',
    messagingSenderId: '452328140275',
    projectId: 'chat-app-e85a4',
    authDomain: 'chat-app-e85a4.firebaseapp.com',
    storageBucket: 'chat-app-e85a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Y5DW9Hwi_p3LgA2uQdg5LvPesWoIOIs',
    appId: '1:452328140275:android:a0a3346219173c901c3686',
    messagingSenderId: '452328140275',
    projectId: 'chat-app-e85a4',
    storageBucket: 'chat-app-e85a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRwT8XdAvmFXRSeA0woFo41O2VzLb9QpY',
    appId: '1:452328140275:ios:fa3bc6e875bd91601c3686',
    messagingSenderId: '452328140275',
    projectId: 'chat-app-e85a4',
    storageBucket: 'chat-app-e85a4.firebasestorage.app',
    iosBundleId: 'com.example.andreopoulosMessasing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRwT8XdAvmFXRSeA0woFo41O2VzLb9QpY',
    appId: '1:452328140275:ios:fa3bc6e875bd91601c3686',
    messagingSenderId: '452328140275',
    projectId: 'chat-app-e85a4',
    storageBucket: 'chat-app-e85a4.firebasestorage.app',
    iosBundleId: 'com.example.andreopoulosMessasing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgv9xkzeAnni2aD4nNtwKHNv9r8NlR2Qc',
    appId: '1:452328140275:web:a466deffb51c3b731c3686',
    messagingSenderId: '452328140275',
    projectId: 'chat-app-e85a4',
    authDomain: 'chat-app-e85a4.firebaseapp.com',
    storageBucket: 'chat-app-e85a4.firebasestorage.app',
  );
}
